import { createMarkdownFromOpenApi } from "@scalar/openapi-to-markdown";
import { createApp } from "./app.js";
import { openApiDocumentConfig, openApiGeneratorOptions } from "./openapi.js";

type OpenApiDocument = ReturnType<
  ReturnType<typeof createApp>["getOpenAPI31Document"]
>;

const generatedFileNotice =
  "<!-- Generated by `pnpm --filter @app/api run docs:generate`. Do not edit by hand. -->";

const documentedMethods = [
  "get",
  "post",
  "put",
  "patch",
  "delete",
  "head",
  "options",
] as const;

type DocumentedMethod = (typeof documentedMethods)[number];

export async function generateApiMarkdownFiles() {
  const app = createApp();
  const document = app.getOpenAPI31Document(
    openApiDocumentConfig,
    openApiGeneratorOptions,
  );
  const files = new Map<string, string>();
  const documentedPaths = Object.keys(document.paths ?? {}).sort();

  files.set("index.md", createIndexMarkdown(document, documentedPaths));

  for (const apiPath of documentedPaths) {
    files.set(
      `${apiPathToRelativeFile(apiPath)}.md`,
      await createPathMarkdown(document, apiPath),
    );
  }

  return files;
}

function createIndexMarkdown(
  document: OpenApiDocument,
  documentedPaths: string[],
) {
  const lines = [
    generatedFileNotice,
    "",
    `# ${document.info.title}`,
    "",
    `- **OpenAPI Version:** \`${document.openapi}\``,
    `- **API Version:** \`${document.info.version}\``,
    "",
  ];

  if (document.info.description) {
    lines.push(document.info.description, "");
  }

  lines.push("## Routes", "");

  for (const apiPath of documentedPaths) {
    const methods = getPathMethods(document.paths?.[apiPath]);
    const label = `${methods.map((method) => method.toUpperCase()).join(", ")} ${apiPath}`;

    lines.push(`- [${label}](${apiPathToRelativeFile(apiPath)}.md)`);
  }

  return normalizeMarkdown(lines.join("\n"));
}

async function createPathMarkdown(document: OpenApiDocument, apiPath: string) {
  const pathItem = document.paths?.[apiPath];
  const routeMarkdown = await createMarkdownFromOpenApi({
    ...document,
    paths: pathItem ? { [apiPath]: pathItem } : {},
  });

  return normalizeMarkdown(
    [
      generatedFileNotice,
      "",
      `# ${apiPath}`,
      "",
      extractPathBody(routeMarkdown),
      "",
    ].join("\n"),
  );
}

function extractPathBody(markdown: string) {
  const withoutSchemas = markdown.replace(/\n## Schemas[\s\S]*$/u, "");
  const operationsStart = withoutSchemas.indexOf("## Operations");

  return operationsStart >= 0
    ? withoutSchemas.slice(operationsStart).trim()
    : withoutSchemas.trim();
}

function getPathMethods(pathItem: object | undefined): DocumentedMethod[] {
  if (!pathItem) {
    return [];
  }

  return documentedMethods.filter((method) => method in pathItem);
}

function apiPathToRelativeFile(apiPath: string) {
  return apiPath.replace(/^\/+/, "").replaceAll("{", "").replaceAll("}", "");
}

function normalizeMarkdown(markdown: string) {
  return `${markdown.trim().replaceAll("\u00a0", " ").replaceAll("\u2014", "-")}\n`;
}
